app/views/main.py
import os
from flask import Blueprint, render_template
from utils.data import MODELS

main_bp = Blueprint('main_bp', __name__, url_prefix='/')

@main_bp.route('/')
def index():
    carousel_images = os.listdir('app/static/img/carousel')
    return render_template('index.html', carousel_images=carousel_images)

@main_bp.route('/studio')
def studio():
    return render_template('studio.html', models=MODELS)

@main_bp.route('/gallery')
def gallery():
    images = os.listdir('app/static/img/gallery')
    return render_template('gallery.html', images=images)

@main_bp.route('/docs')
def docs():
    return render_template('docs.html')

app/views/studio.py
import base64
import logging
import os
import tempfile
from flask import jsonify, request, Blueprint, render_template, current_app
from nst import neural_style_transfer
from editor import enhance_image
from config import Config
from utils.generate import Model, ModelError
from utils.nst_utils import (process_image_data, write_temp_file, 
                             cleanup_temp_files, generate_unique_file_name)


studio_bp = Blueprint('studio_bp', __name__, url_prefix='/studio')


HF_API_KEY = os.getenv('HF_API_KEY')
HF_ENDPOINTS = {
    'stable-diffusion-v15': os.getenv('STABLE_DIFFUSION_V15'),
    'stable-diffusion-v21': os.getenv('STABLE_DIFFUSION_V21'),
    'stable-diffusion-xl-base-1.0': os.getenv('STABLE_DIFFUSION_XL_BASE_1.0'),
    'dreamlike-photo-real': os.getenv('DREAMLIKE_PHOTO_REAL'),
    'dream-shaper': os.getenv('DREAM_SHAPER'),
    'realistic-vision-v14': os.getenv('REALISTIC_VISION_V14'),
    'nitro-diffusion': os.getenv('NITRO_DIFFUSION'),
    'dreamlike-anime': os.getenv('DREAMLIKE_ANIME_V10'),
    'anything-v5': os.getenv('ANYTHING_V5'),
}


@studio_bp.route('/result')
def result():
    return render_template('result.html')


@studio_bp.route('/enhance', methods=['POST'])
def enhance():
    data = request.get_json()
    if not data or 'input_image' not in data:
        return jsonify({'error': 'Missing input_image in request'}), 400

    content_data = data['input_image']

    try:
        upsampler = current_app.upsampler
        result_image, was_enhanced = enhance_image(content_data, upsampler)
        if not was_enhanced:
            return jsonify({'error': 'Image is already enhanced', 'was_enhanced': False}), 200
    except Exception as e:
        logging.error(f"An error occurred: {e}")
        return jsonify({'error': 'Failed to enhance image'}), 500

    return jsonify({
        'result': f"data:image/png;base64,{result_image}",
        'was_enhanced': True
    })


@studio_bp.route('/generate', methods=['POST'])
def generate():
    try:
        data = request.get_json()
        print(data)

        prompt = data.get('prompt', '')
        if not prompt:
            return jsonify({'error': 'Prompt is required'}), 400
        
        negative_prompt = data.get('negativePrompt', '')
        guidance_scale = data.get('guidanceScale', 7)
        inference_steps = data.get('inferenceSteps', 30)
        height = data.get('height', 512)
        width = data.get('width', 512)
        model_name = data.get('model', 'realistic-vision-v14')

        print(f"Model: {model_name}, Prompt: {prompt}, Negative Prompt: {negative_prompt}, Guidance Scale: {guidance_scale}, Inference Steps: {inference_steps}, Height: {height}, Width: {width}")

        model = Model(HF_ENDPOINTS[model_name], prompt, negative_prompt, guidance_scale, inference_steps, height, width)
        base64_image = model.generate()
        return jsonify({'result': f"data:image/png;base64,{base64_image}"})
    except ModelError as e:
        logging.error(f"An error occurred: {e}")
        return jsonify({'error': 'Failed to generate image'}), 500


@studio_bp.route('/merge', methods=['POST'])
def merge():
    data = request.get_json()
    content_data = data['contentImage']  # base64 encoded string or URL
    style_data = data['styleImage']  # base64 encoded string or URL

    try:
        # Process content and style images
        content_image_data, content_extension = process_image_data(content_data)
        style_image_data, style_extension = process_image_data(style_data)

        # Create temporary files for processing
        with tempfile.NamedTemporaryFile(delete=False, suffix=f'.{content_extension}') as content_temp_file, \
             tempfile.NamedTemporaryFile(delete=False, suffix=f'.{style_extension}') as style_temp_file:

            write_temp_file(content_temp_file, content_image_data)
            write_temp_file(style_temp_file, style_image_data)

            # Perform neural style transfer and generate result
            result_image_base64 = perform_neural_style_transfer(content_temp_file.name, style_temp_file.name, data)

            # Close temporary files before cleanup
            content_temp_file.close()
            style_temp_file.close()
            
            # Cleanup and return result
            cleanup_temp_files([content_temp_file.name, style_temp_file.name])
            return jsonify({'result': f"data:image/jpeg;base64,{result_image_base64}"})
    except Exception as e:
        logging.error(f"An error occurred: {e}")
        return jsonify({'error': 'Failed to process images'}), 500


def perform_neural_style_transfer(content_path, style_path, settings):
    """Performs neural style transfer with the given settings and returns
    the result as a base64 encoded string.
    """
    original_file_name = settings.get('settings', {}).get('outputFileName', 'output')
    img_format = settings.get('settings', {}).get('outputImageFormat', '.jpg')

    # Generate a unique file name if necessary
    output_file_name = generate_unique_file_name(Config.OUTPUT_FOLDER, original_file_name, img_format)

    config = {
        'content_img_path': content_path,
        'style_img_path': style_path,
        'output_file_name': output_file_name,
        'img_format': img_format,
        'height': int(settings.get('settings', {}).get('nstImageHeight', 512)),
        'content_weight': float(settings.get('settings', {}).get('nstContentWeight', 1.0)),
        'style_weight': float(settings.get('settings', {}).get('nstStyleWeight', 30)),
        'tv_weight': float(settings.get('settings', {}).get('nstTotalVariationWeight', 1e-1)),
        'num_iterations': int(settings.get('settings', {}).get('nstIterations', 10)),
    }
    config['output_img_path'] = os.path.join(Config.OUTPUT_FOLDER, config['output_file_name'])

    # Perform neural style transfer using the provided configuration
    neural_style_transfer(config)

    # Read the result and encode it into base64
    with open(config['output_img_path'], "rb") as result_image_file:
        return base64.b64encode(result_image_file.read()).decode('utf-8')

app/templates/base.html
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>FX / {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cropper.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Hero-Features-icons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Lightbox-Gallery-baguetteBox.min.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/loader.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.svg') }}">
</head>

<body style="background: var(--bs-emphasis-color);">
    <nav class="navbar navbar-expand-md text-light bg-transparent py-3" style="border-style: solid;border-top-style: none;border-right-style: none;border-bottom: 1px solid var(--bs-dark-border-subtle);border-left-style: none;font-weight: bold;" data-bs-theme="dark">
        <div class="container"><a class="navbar-brand link-body-emphasis d-flex align-items-center" href="{{ url_for('main_bp.index')}}"><img src="{{ url_for('static', filename='img/brand.png') }}" style="max-height: 60px;"></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-5"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-5">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item" style="margin-right: 20px;"><a class="nav-link active" href="{{ url_for('main_bp.studio') }}">Studio</a></li>
                    <li class="nav-item" style="margin-right: 20px;"><a class="nav-link" href="{{ url_for('main_bp.gallery') }}">Gallery</a></li>
                    <li class="nav-item" style="margin-right: 20px;"><a class="nav-link" href="{{ url_for('main_bp.docs') }}">Docs</a></li>
                </ul>
            </div>
        </div>
    </nav>

    {% block loader %}{% endblock %}
    {% block content %}{% endblock %}

    <footer class="text-center bg-dark">
        <div class="container text-white py-4 py-lg-5">
            <p class="text-white mb-0">Copyright © 2024 Fusion<span style="color: #A6BC09; font-family: 'Brush Script MT', cursive; font-size:1.5em">X</span></p>
        </div>
    </footer>

    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/cropper.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="module"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6" type="module"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/Lightbox-Gallery-baguetteBox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/Lightbox-Gallery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
    <script src="{{ url_for('static', filename='js/editor.js') }}"></script>
</body>

</html>

app/templates/docs.html
{% extends 'base.html' %}

{% block title %}Docs{% endblock %}

{% block content %}
<section class="py-4 py-xl-5" style="color: var(--bs-body-bg);">
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-md-10 col-xl-8 text-center d-flex d-sm-flex d-md-flex justify-content-center align-items-center mx-auto justify-content-md-start align-items-md-center justify-content-xl-center">
                <div>
                    <h2 class="text-capitalize fs-1 fw-bolder mb-3" style="line-height: 2;letter-spacing: 5px;font-weight: bold;">Learning The NST Model</h2>
                    <p class="font-monospace fs-5">Neural Style Transfer (NST) merges two images, namely: a "content" image (C) and a "style" image (S), to create a "generated" image (G). The generated image G combines the "content" of the image C with the "style" of image S.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div style="text-align: center;"><img src="{{ url_for('static', filename='img/nst_example.png') }}" style="max-width: 90%;">
        <hr>
    </div>
</div>

<div class="container text-light doc-container">
    <div style="text-align: left;">
        <!-- Toggle Button -->
        <div><h1 class="fs-3 fw-bolder" style="text-align: left;" data-bs-toggle="collapse" data-bs-target="#collapseTransferLearning">1 - Transfer Learning</h1></div>

        <!-- Collapsible Element -->
            <div class="text-light">
                <p>NST uses a previously trained convolutional network, and builds on top of that. The idea of using a network trained on a different task and applying it to a new task is called transfer learning.&nbsp;We will use VGG-19, a 19-layer version of the VGG network. This model has already been trained on the very large ImageNet database, and has learned to recognize a variety of low level features (at the shallower layers) and high level features (at the deeper layers).</p>
                <h1 class="fs-5 fw-bolder" style="text-align: left;">1.1 - NST Algorithm</h1>
                <p>Build the Neural Style Transfer (NST) algorithm in three steps:</p>
                <ul>
                    <li>Build the content cost function \(J_{content}(C,G)\)</li>
                    <li>Build the style cost function \(J_{style}(S,G)\)</li>
                    <li>Put it all together to get \(J(G) = \alpha J_{content}(C,G) + \beta J_{style}(S,G)\)</li>
                </ul>
            </div>
        <hr style="color: #DBF227;">
    </div>
</div>

<div class="container text-light doc-container">
    <!-- Toggle Container -->
    <div><h1 class="fs-3 fw-bolder" style="text-align: left;" data-bs-toggle="collapse" data-bs-target="#nstWorkFlow">2 - NST Workflow</h1></div>

    <!-- Collapsible Element -->
        <div class="row row-cols-1 row-cols-md-2">
            <div class="col" style="border-top-style: none;border-top-color: #019587;border-right-style: none;border-right-color: #019587;border-bottom-style: none;border-bottom-color: #019587;border-left-style: none;border-left-color: #019587;">
                <div class="text-start" style="color: #D6D58E;border-radius: 10px;max-width: 90%;border-style: none;border-top-style: none;border-right-style: none;border-bottom-style: none;border-bottom-color: #019587;border-left-style: none;"><code style="color: #D6D58E;border-radius: 10px;border-width: 1px;border-color: #019587;border-top-color: #019587;border-right-color: #019587;border-bottom-color: #019587;border-left-style: none;"><br><br><strong>def train_step(generated_image):</strong>&nbsp; <br>&nbsp; &nbsp; with tf.GradientTape() as tape:<br><br><em><span style="color: var(--jp-mirror-editor-comment-color);">&nbsp; &nbsp; &nbsp; &nbsp; # Compute a_G as the vgg_model_outputs</span></em><br>&nbsp; &nbsp; &nbsp; &nbsp; a_G = vgg_model_outputs(generated_image)<br><br><em><span style="color: var(--jp-mirror-editor-comment-color);">&nbsp; &nbsp; &nbsp; &nbsp; # Compute the style cost</span></em><br>&nbsp; &nbsp; &nbsp; &nbsp; J_style = compute_style_cost(a_S, a_G, STYLE_LAYERS)<br>&nbsp; &nbsp;<br><em><span style="color: var(--jp-mirror-editor-comment-color);">&nbsp; &nbsp; &nbsp; &nbsp; # Compute the content cost</span></em><br>&nbsp; &nbsp; &nbsp; &nbsp; J_content = compute_content_cost(a_C, a_G)<br>&nbsp;<br><em><span style="color: var(--jp-mirror-editor-comment-color);">&nbsp; &nbsp; &nbsp; &nbsp; # Compute the total cost</span></em><br>&nbsp; &nbsp; &nbsp; &nbsp; J = total_cost(J_content, J_style, alpha, beta)<br>&nbsp; <br>&nbsp; grad = tape.gradient(J, generated_image)<br>&nbsp; optimizer.apply_gradients([(grad, generated_image)])<br><br>&nbsp; generated_image.assign(clip_0_1(generated_image))<br>&nbsp; return J<br><br>generated_image = tf.Variable(generated_image)<br><br>epochs = 2501<br>for i in range(epochs):<br>&nbsp; train_step(generated_image)</code></div>
            </div>
            <div class="col">
                <div class="text-center"><img class="rounded w-100 h-100 fit-cover" style="min-height: 300px;max-width: 90%;border-radius: 10px;" src="{{ url_for('static', filename='img/nn.png') }}" width="636" height="300" loading="lazy">
                    <p class="text-light"><br><strong>Figure 3:</strong> <em>NST Architecture Workflow</em></p>
                </div>
            </div>
        </div>
    <hr style="color: #DBF227;">
</div>


<div class="container text-light doc-container">
        <!-- Toggle Button -->
        <div><h1 class="fs-3 fw-bolder" style="text-align: left; cursor: pointer;" data-bs-toggle="collapse" data-bs-target="#collapseContentCost">3 - Content Cost Function <span class="arrow">&#x25BC;</span></h1></div>

        <!-- Collapsible Element -->
        <div id="collapseContentCost" class="collapse">
            <div class="text-light">
                <p>One goal we should aim for when performing NST is for the content in generated image G to match the content of image C. A method to achieve this is to calculate the content cost function, which will be defined as:<br><br>\(J_{content}(C,G) =&nbsp;\frac{1}{4 \times n_H \times n_W \times n_C}\sum _{ \text{all entries}} (a^{(C)} - a^{(G)})^2\)</p>
                <ul class="text-white">
                    <li>\(n_H, n_W\) and \(n_C\) are the height, width and number of channels of the hidden layer chosen, and appear in normalization term in the cost.</li>
                    <li>For clarity, note that \(a^{(C)}\) and \(a^{(G)}\) are the 3D volumes corresponding to a hidden layer's activations.</li>
                    <li>In order to compute the cost \(J_{content}(C,G)\), it is convenient to unroll these 3D volumes into a 2D matrix, as shown.</li>
                </ul>

                <div style="text-align: center;"><img src="{{ url_for('static', filename='img/NST_LOSS.png') }}" style="border-radius: 10px;max-width: 50%;margin-top: 20px;" loading="lazy">
                    <p class="text-light"><br><strong>Figure 1:</strong> Unrolling a 3D volume into a 2D matrix</p>
                </div>

            </div>
        </div>
        <hr style="color: #DBF227;">
    </div>
</div>

<div class="container text-light doc-container">
        <!-- Toggle Button -->
        <div><h1 class="fs-3 fw-bolder" style="text-align: left; cursor: pointer;" data-bs-toggle="collapse" data-bs-target="#collapseStyleCost">4 - Style Cost Function <span class="arrow">&#x25BC;</span></h1></div>
        
        <!-- Collapsible Element -->
        <div id="collapseStyleCost" class="collapse">
            <div class="text-light">
                <p>The style matrix is also called a "Gram matrix." The Gram matrix G of a set of vectors \((v_{1},\dots ,v_{n})\) is the matrix of dot products, whose entries are \({\displaystyle G_{ij} = v_{i}^T v_{j} = np.dot(v_{i}, v_{j})&nbsp;}\).&nbsp;<br><br>\(G_{ij}\) compares how similar \(v_i\) is to \(v_j\): if highly similar, we would expect them to have a large dot product, and thus for \(G_{ij}\) to be large.&nbsp;<br><br>\(\mathbf{G}_{gram} = \mathbf{A}_{unrolled} \mathbf{A}_{unrolled}^T\)</p>
                <ul class="text-white">
                    <li>The diagonal elements \(G_{(gram)ii}\) measure how "active" a filter \(i\) is. </li>
                    <li><span style="color: rgb(248, 249, 250);">For example, suppose filter \(i\) is detecting vertical textures in the image. Then \(G_{(gram)ii}\) measures how common vertical textures are in the image as a whole.</span></li>
                    <li><span style="color: rgb(248, 249, 250);">If \(G_{(gram)ii}\) is large, this means that the image has a lot of vertical texture.&nbsp;</span></li>
                </ul>
                <p>By capturing the prevalence of different types of features (\(G_{(gram)ii}\)), as well as how much different features occur together (\(G_{(gram)ij}\)), the Style matrix \(G_{gram}\) measures the style of an image.</p>
                
                <div style="text-align: center;"><img src="{{ url_for('static', filename='img/NST_GM.png') }}" style="border-radius: 10px;max-width: 50%;margin-top: 20px;" loading="lazy">
                    <p class="text-light"><br><strong>Figure 2:</strong> Computing the Style matrix by multiplying the "unrolled" filter matrix with its transpose&nbsp;</p>
                    <p class="text-light" style="text-align: left;"><br>The result is a matrix of dimension \((n_C,n_C)\) where \(n_C\) is the number of filters (channels). The value \(G_{(gram)i,j}\) measures how similar the activations of filter \(i\) are to the activations of filter \(j\).&nbsp;</p>
                </div>

            </div>
        </div>
        <hr style="color: #DBF227;">
    </div>
</div>

<div class="container text-light doc-container">
        <!-- Toggle Button -->
        <div><h1 class="fs-3 fw-bolder" style="text-align: left; cursor: pointer;" data-bs-toggle="collapse" data-bs-target="#collapseTotalCost">5 - Total Cost Minimization <span class="arrow">&#x25BC;</span></h1></div>

        <!-- Collapsible Element -->
        <div id="collapseTotalCost" class="collapse">
            <div>
                <p class="text-white">Minimize the distance between the Gram matrix of the "style" image S and the Gram matrix of the "generated" image G. For a single hidden layer \(a^{[l]}\), the corresponding style cost for this layer is defined as:<br><br>\(J_{style}^{[l]}(S,G) = \frac{1}{4 \times {n_C}^2 \times (n_H \times n_W)^2} \sum _{i=1}^{n_C}\sum_{j=1}^{n_C}(G^{(S)}_{(gram)i,j} - G^{(G)}_{(gram)i,j})^2\tag{2} \)</p>
                <ul class="text-white">
                    <li>\(G_{gram}^{(S)}\) Gram matrix of the "style" image.</li>
                    <li>\(G_{gram}^{(G)}\) Gram matrix of the "generated" image.</li>
                </ul>
                <p class="text-white">\(J(G) = \alpha J_{content}(C,G) + \beta J_{style}(S,G)\)</p>
            </div>
        </div>
        <hr style="color: #DBF227;">
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="py-4 py-xl-5" style="color: var(--bs-body-bg);">
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-md-10 col-xl-8 text-center d-flex d-sm-flex d-md-flex justify-content-center align-items-center mx-auto justify-content-md-start align-items-md-center justify-content-xl-center">
                <div> 
                    <h1 class="text-capitalize fs-1 fw-bolder mb-3" style="line-height: 2;letter-spacing: 5px; font-weight: 700;">fusion <span style="color: #A6BC09; font-family: 'Brush Script MT', cursive; font-size:1.5em">X</span>perience</h1>
                    <figure>
                        <blockquote class="blockquote">
                            <p class="font-monospace mb-0">Unlock new dimensions of visual creativity. Remix iconic styles, generate beautiful images, and find your artistic voice - where your creativity and our tech converge.</p>
                        </blockquote>
                        <figcaption class="blockquote-footer">The fusionX Team</figcaption>
                    </figure>
                    <hr><a class="btn btn-dark btn-lg fs-6 fw-semibold border rounded-pill border-2" role="button" href="{{ url_for('main_bp.studio') }}">Go to Studio</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div style="height: 700px;background: url(&quot;static/img/header.png&quot;) center / cover no-repeat;"></div>
    <div class="container h-100 position-relative" style="top: -50px;">
        <div class="row gy-5 gy-lg-0 row-cols-1 row-cols-md-2 row-cols-lg-3">
            <div class="col">
                <div class="card" style="background: var(--bs-gray-100);text-align: center;">
                    <div class="card-body pt-5 p-4">
                        <h4 class="card-title" style="font-weight: bold;color: #A6BC09;">Instant Style Transfer</h4>
                        <h6 class="text-muted card-subtitle mb-2">Effortless Artistic Makeover</h6>
                        <p class="card-text">Upload your photo, choose an art style, and instantly transform it. Create your masterpiece in seconds!</p>
                    </div>
                    <div class="card-footer p-4 py-3"><a href="{{ url_for('main_bp.studio') }}">Go to Studio&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right">
                                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"></path>
                            </svg></a></div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="background: var(--bs-gray-100);text-align: center;">
                    <div class="card-body pt-5 p-4">
                        <h4 class="card-title" style="font-weight: bold;color: #A6BC09;">Extensive Style Gallery</h4>
                        <h6 class="text-muted card-subtitle mb-2">Diverse Artistic Choices</h6>
                        <p class="card-text">Explore our gallery of styles ranging from classical to modern art. Pick the perfect one for your photo and let the magic happen!</p>
                    </div>
                    <div class="card-footer p-4 py-3"><a href="{{ url_for('main_bp.gallery') }}">Explore Gallery&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right">
                                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"></path>
                            </svg></a></div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="background: var(--bs-gray-100);text-align: center;">
                    <div class="card-body pt-5 p-4">
                        <h4 class="card-title" style="font-weight: bold;color: #A6BC09;">Discover NST Intuitions</h4>
                        <h6 class="text-muted card-subtitle mb-2">The Model Behind NST</h6>
                        <p class="card-text">Learn how to store and transfer styles between images using Deep Learning especially with Transfer Learning through the VGG-16 network!</p>
                    </div>
                    <div class="card-footer p-4 py-3"><a href="{{ url_for('main_bp.docs') }}">Learn Now&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right">
                                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"></path>
                            </svg></a></div>
                </div>
            </div>
        </div>
        <hr style="color: #CCEA8D;">
    </div>
</section>

<div class="container">
    <div class="carousel slide" data-bs-ride="carousel" id="carousel-1">
        <div class="carousel-inner">
            {% for image in carousel_images | batch(3, '&nbsp;') %}
                <div class="carousel-item {% if loop.first %}active{% endif %}">
                    <div class="d-flex">
                        {% for img in image %}
                            <img class="flex-fill d-block carousel-img" alt="Slide Image" src="{{ url_for('static', filename='img/carousel/' + img) }}" style="width:33.33%;">
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div>
            <a class="carousel-control-prev" href="#carousel-1" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                <span class="visually-hidden">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-1" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon"></span>
                <span class="visually-hidden">Next</span>
            </a>
        </div>
        <ol class="carousel-indicators">
            {% for _ in carousel_images | batch(3, '&nbsp;') %}
                <li data-bs-target="#carousel-1" data-bs-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}